hbase:
  config:
    hbase.zookeeper.quorum: ip
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000
    hbase:
      client:
        retries:
          number: 3
    zookeeper:
      recovery:
        retry: 3