package com.helloxin.model.alocal;

import java.util.ArrayList;
import java.util.Arrays;

public class KktDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkt.id
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkt.test
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    private String test;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkt.id
     *
     * @return the value of kkt.id
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkt.id
     *
     * @param id the value for kkt.id
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkt.test
     *
     * @return the value of kkt.test
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public String getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkt.test
     *
     * @param test the value for kkt.test
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public void setTest(String test) {
        this.test = test == null ? null : test.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkt
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public static KktDO.Builder builder() {
        return new KktDO.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kkt
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private KktDO obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public Builder() {
            this.obj = new KktDO();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column kkt.id
         *
         * @param id the value for kkt.id
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column kkt.test
         *
         * @param test the value for kkt.test
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public Builder test(String test) {
            obj.setTest(test);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public KktDO build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table kkt
     *
     * @mbg.generated Tue Mar 10 14:52:09 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        test("test", "test", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table kkt
         *
         * @mbg.generated Tue Mar 10 14:52:09 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}