package com.helloxin.mapper.local;

import com.helloxin.model.local.PpkDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PpkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int insert(PpkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int insertSelective(@Param("record") PpkDO record, @Param("selective") PpkDO.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    PpkDO selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PpkDO.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    PpkDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int updateByPrimaryKeySelective(@Param("record") PpkDO record, @Param("selective") PpkDO.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int updateByPrimaryKey(PpkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int batchInsert(@Param("list") List<PpkDO> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int batchInsertSelective(@Param("list") List<PpkDO> list, @Param("selective") PpkDO.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int upsert(PpkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppk
     *
     * @mbg.generated Tue Mar 10 14:49:00 CST 2020
     */
    int upsertSelective(@Param("record") PpkDO record, @Param("selective") PpkDO.Column... selective);
}